language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm
  - nightly

matrix:
  allow_failures:
      - php: 7.0
#      - php: hhvm
      - php: nightly
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction
  - php composer.phar update --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls